language: python
python:
  - "3.4"
  - "3.6"
  - "nightly"
env:
  - PYTHONPATH=$PYTHONPATH:$(pwd)
install:
  - pip install -r requirements.txt
script:
  - cd test
  - pytest
matrix:
  allow_failures:
    - python: "nightly"
notifications:
  email: false
